spring:
  application:
    name: scw-register
    
server:
  port: 8761
  
  
eureka:
  instance:
    hostname: 47.103.34.16
  client:
    register-with-eureka: false 
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  
